build:
  environment:
    php: 7.2.13
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
    coverage:
      tests:
        override:
          - command: ./vendor/bin/simple-phpunit --coverage-clover=coverage.xml
            coverage:
              file: coverage.xml
              format: clover

filter:
  paths: ["src/*"]
