language: php

cache:
  directories:
    # backend
    - $HOME/.composer/cache/files
    - vendor

    # frontend
    - node_modules

matrix:
  fast_finish: true
  include:
    # target version
    - php: 7.4
      env:
        - COVERAGE=true

before_install:
  # backend
  - if [[ $COVERAGE == false ]]; then phpenv config-rm xdebug.ini; fi
  - composer validate
  - php --version

  # frontend
  - nvm install v12 # set node version to 12
  - node --version

install:
  # backend
  - composer install

  # install local-php-security-checker
  -  wget -O local-php-security-checker https://github.com/fabpot/local-php-security-checker/releases/download/v1.0.0/local-php-security-checker_1.0.0_linux_amd64
  - chmod +x local-php-security-checker

  # frontend
  - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
  - npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME_AUTH_TOKEN
  - yarn install

# prepare tests
before_script:
  # frontend
  - yarn encore production

# execute tests
script:
  # backend
  - php vendor/bin/requirements-checker
  - ./local-php-security-checker
  - if [[ "$COVERAGE" == true ]]; then ./vendor/bin/php-cs-fixer fix --diff --dry-run -v; fi
  - php bin/console lint:yaml config
  - php bin/console lint:twig templates
  - php vendor/bin/simple-phpunit

  # frontend
  - yarn audit --groups dependencies
